version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tseda-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: tseda-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: